package org.domain.delegator.entity;

// Generated 00:56:58 13/09/2009 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Archived generated by hbm2java
 */
@Entity
@Table(name = "archived", catalog = "dropdb")
public class Archived implements java.io.Serializable {

	private int tid;
	private Archived archivedByParentTaskId;
	private Archived archivedByRootTaskId;
	private Employee employee;
	private Date cdate;
	private Date edate;
	private String title;
	private String description;
	private String attachment;
	private String status;
	private Integer parallel;
	private Set<Archived> archivedsForRootTaskId = new HashSet<Archived>(0);
	private Set<Archived> archivedsForParentTaskId = new HashSet<Archived>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Archived() {
	}

	public Archived(int tid, Archived archivedByParentTaskId,
			Archived archivedByRootTaskId, Employee employee, Date cdate,
			Date edate, String title, String status) {
		this.tid = tid;
		this.archivedByParentTaskId = archivedByParentTaskId;
		this.archivedByRootTaskId = archivedByRootTaskId;
		this.employee = employee;
		this.cdate = cdate;
		this.edate = edate;
		this.title = title;
		this.status = status;
	}

	public Archived(int tid, Archived archivedByParentTaskId,
			Archived archivedByRootTaskId, Employee employee, Date cdate,
			Date edate, String title, String description, String attachment,
			String status, Integer parallel,
			Set<Archived> archivedsForRootTaskId,
			Set<Archived> archivedsForParentTaskId, Set<Employee> employees) {
		this.tid = tid;
		this.archivedByParentTaskId = archivedByParentTaskId;
		this.archivedByRootTaskId = archivedByRootTaskId;
		this.employee = employee;
		this.cdate = cdate;
		this.edate = edate;
		this.title = title;
		this.description = description;
		this.attachment = attachment;
		this.status = status;
		this.parallel = parallel;
		this.archivedsForRootTaskId = archivedsForRootTaskId;
		this.archivedsForParentTaskId = archivedsForParentTaskId;
		this.employees = employees;
	}

	@Id
	@Column(name = "Tid", unique = true, nullable = false)
	@NotNull
	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ParentTaskId", nullable = false)
	@NotNull
	public Archived getArchivedByParentTaskId() {
		return this.archivedByParentTaskId;
	}

	public void setArchivedByParentTaskId(Archived archivedByParentTaskId) {
		this.archivedByParentTaskId = archivedByParentTaskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rootTaskId", nullable = false)
	@NotNull
	public Archived getArchivedByRootTaskId() {
		return this.archivedByRootTaskId;
	}

	public void setArchivedByRootTaskId(Archived archivedByRootTaskId) {
		this.archivedByRootTaskId = archivedByRootTaskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CreatorId", nullable = false)
	@NotNull
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CDate", nullable = false, length = 19)
	@NotNull
	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EDate", nullable = false, length = 19)
	@NotNull
	public Date getEdate() {
		return this.edate;
	}

	public void setEdate(Date edate) {
		this.edate = edate;
	}

	@Column(name = "Title", nullable = false)
	@NotNull
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Attachment")
	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	@Column(name = "status", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "parallel")
	public Integer getParallel() {
		return this.parallel;
	}

	public void setParallel(Integer parallel) {
		this.parallel = parallel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "archivedByRootTaskId")
	public Set<Archived> getArchivedsForRootTaskId() {
		return this.archivedsForRootTaskId;
	}

	public void setArchivedsForRootTaskId(Set<Archived> archivedsForRootTaskId) {
		this.archivedsForRootTaskId = archivedsForRootTaskId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "archivedByParentTaskId")
	public Set<Archived> getArchivedsForParentTaskId() {
		return this.archivedsForParentTaskId;
	}

	public void setArchivedsForParentTaskId(
			Set<Archived> archivedsForParentTaskId) {
		this.archivedsForParentTaskId = archivedsForParentTaskId;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "archived_doneby", catalog = "dropdb", joinColumns = { @JoinColumn(name = "Tid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Eid", nullable = false, updatable = false) })
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
