package org.domain.delegator.entity;

// Generated 00:56:58 13/09/2009 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Divisions generated by hbm2java
 */
@Entity
@Table(name = "divisions", catalog = "dropdb")
public class Divisions implements java.io.Serializable {

	private int divId;
	private Employee employee;
	private String name;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Divisions() {
	}

	public Divisions(int divId, Employee employee, String name) {
		this.divId = divId;
		this.employee = employee;
		this.name = name;
	}

	public Divisions(int divId, Employee employee, String name,
			Set<Employee> employees) {
		this.divId = divId;
		this.employee = employee;
		this.name = name;
		this.employees = employees;
	}

	@Id
	@Column(name = "DivId", unique = true, nullable = false)
	@NotNull
	public int getDivId() {
		return this.divId;
	}

	public void setDivId(int divId) {
		this.divId = divId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ManagerId", nullable = false)
	@NotNull
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "Name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "div_worker", catalog = "dropdb", joinColumns = { @JoinColumn(name = "DivId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Eid", nullable = false, updatable = false) })
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
