package org.domain.delegator.entity;

// Generated 21:03:27 09/08/2009 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.NotNull;

/**
 * TasksCId generated by hbm2java
 */
@Embeddable
public class TasksCId implements java.io.Serializable {

	private int tid;
	private int parent;

	public TasksCId() {
	}

	public TasksCId(int tid, int parent) {
		this.tid = tid;
		this.parent = parent;
	}

	@Column(name = "Tid", nullable = false)
	@NotNull
	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	@Column(name = "Parent", nullable = false)
	@NotNull
	public int getParent() {
		return this.parent;
	}

	public void setParent(int parent) {
		this.parent = parent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TasksCId))
			return false;
		TasksCId castOther = (TasksCId) other;

		return (this.getTid() == castOther.getTid())
				&& (this.getParent() == castOther.getParent());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTid();
		result = 37 * result + this.getParent();
		return result;
	}

}
